"""
GlobalConstantValue constants from APK's GlobalConstantValue.java
These constants define the protocol commands and values for STB communication.
"""
from __future__ import annotations


# Magic code for STB broadcast info
G_MS_BROADCAST_INFO_MAGIC_CODE = "39WwijOog54a"
G_MS_BROADCAST_INFO_MAGIC_CODE_LEN = 12
G_MS_BROADCAST_INFO_XOR_VALUE = 91  # 0x5B

# Ports
G_MS_BROADCAST_PORT = 25860
G_MS_LOGIN_DEFAULT_PORT_NUM = 20000
UPNP_PORT_START = 20001
UPNP_PORT_END = 20005

# Data lengths
STB_LOGIN_INFO_DATA_LENGTH = 108
GS_CONTROL_DATA_MSG_LENGTH = 16
G_MSCREEN_CONTROL_DATA_HEADER_LEN = 4
G_MSCREEN_CONTROL_DATA_HEADER_STR = "GCDH"
COMPRESS_CONTROL_STRING = "BegC"

# Socket frame constants
SOCKET_HEADER_START_FLAG = "Start"
SOCKET_HEADER_END_FLAG = "End"
MAX_DATA_LENGTH_BIT = 7

# Buffer lengths
BUFF_LENGTH_RECEIVE_DATA_PER_TIME = 2048
BUFF_LENGTH_RECEIVE_DATA_TOTAL = 8388608

# Timeouts
SOCKET_TCP_TIMEOUT = 3000
BACK_KEY_EXIT_TIMEOUT = 2000

# Connect types
CONNECT_TYEP_AUTO_LOGIN = 0
CONNECT_TYEP_IP_LOGIN = 1

# Connection error codes
CONNECT_STB_ERROR_UNKONWN_ERROR = -1
CONNECT_STB_ERROR_NOT_RESPONSE = -2
CONNECT_STB_ERROR_NOT_REACHABLE = -3
CONNECT_STB_ERROR_NOT_VALID = -4
CONNECT_STB_ERROR_IP_ERROR = -5
CONNECT_STB_ERROR_SW_VERSION_ERROR = -6
CONNECT_STB_ERROR_STB_IS_FULL = -7
CONNECT_STB_ERROR_HAND_SHARK_ERROR = -8
CONNECT_STB_ERROR_SERVER_IP_NON_EXIST = -9
CONNECT_STB_ERROR_DATA_TRANSMISSION_FAIL = -10

# Request message types (GMS_MSG_REQUEST_*)
GMS_MSG_REQUEST_CHANNEL_LIST = 0
GMS_MSG_REQUEST_EVENT_TIMER = 1
GMS_MSG_REQUEST_SLEEP_TIMER = 2
GMS_MSG_REQUEST_PLAYING_CHANNEL = 3
GMS_MSG_REQUEST_PROGRAM_EPG = 5
GMS_MSG_REQUEST_RS232_DATA_DEBUG = 6
GMS_MSG_REQUEST_CUR_USER_DATA_DEBUG = 7
GMS_MSG_REQUEST_CHANNEL_DATA_DEBUG = 8
GMS_MSG_REQUEST_FLASH_DATA_DEBUG = 9
GMS_MSG_REQUEST_SCREENSHOT_DEBUG = 10
GMS_MSG_REQUEST_STB_TIME = 11
GMS_MSG_REQUEST_FAV_GROUP_NAMES = 12
GMS_MSG_REQUEST_CONTROL_SETTING = 13
GMS_MSG_REQUEST_CHANNEL_LIST_TYPE = 14
GMS_MSG_REQUEST_STB_INFO = 15
GMS_MSG_REQUEST_STB_SETTING_LOGIN = 16
GMS_MSG_REQUEST_TV_RADIO_TYPE = 17
GMS_MSG_REQUEST_CHANNEL_SORT_TYPE = 18
GMS_MSG_REQUEST_MUTE_STATE = 19
GMS_MSG_REQUEST_CONTROL_PASSWORD_SWITCH = 20
GMS_MSG_REQUEST_UPDATE_HEADER = 21
GMS_MSG_REQUEST_SAT_LIST = 22
GMS_MSG_REQUEST_SAT_SELECT_NO = 23
GMS_MSG_REQUEST_TP_LIST = 24
GMS_MSG_REQUEST_RS232_PRINTED_DATA = 25
GMS_MSG_REQUEST_SOCKET_KEEP_ALIVE = 26
GMS_MSG_REQUEST_PVR_LIST = 27
GMS_MSG_REQUEST_MY_IP_FROM_STB = 28
GMS_MSG_REQUEST_STB_SCREENSHOT_DATA_INFO = 29
GMS_MSG_REQUEST_LOGIN_INFO = 998
GMS_MSG_REQUEST_MAX_VALUE = 999

# Do message types (GMS_MSG_DO_*)
GMS_MSG_DO_CHANNEL_SWITCH = 1000
GMS_MSG_DO_CHANNEL_RENAME = 1001
GMS_MSG_DO_CHANNEL_DELETE = 1002
GMS_MSG_DO_CHANNEL_LOCK = 1003
GMS_MSG_DO_CHANNEL_FAV_MARK = 1004
GMS_MSG_DO_CHANNEL_MOVE = 1005
GMS_MSG_DO_CHANNEL_LIST_SORT = 1006
GMS_MSG_DO_CHANNEL_LIST_TYPE_CHANGED = 1007
GMS_MSG_DO_PLAYING_CHANNEL_PASSWORD_CHECK = 1008
GMS_MSG_DO_SAT2IP_CHANNEL_PLAY = 1009
GMS_MSG_DO_CHANNEL_LIST_UPDATE = 1010
GMS_MSG_DO_FAV_CHANNEL_DELETE = 1011
GMS_MSG_DO_SAT2IP_PLAY_STOP = 1012
GMS_MSG_DO_EVENT_TIMER_DELETE = 1020
GMS_MSG_DO_EVENT_TIMER_ADD = 1021
GMS_MSG_DO_EVENT_TIMER_EDIT = 1022
GMS_MSG_DO_REPEATE_EVENT_TIMER_SAVE = 1023
GMS_MSG_DO_FACTORY_DEFAULT_ALL = 1030
GMS_MSG_DO_FACTORY_DEFAULT_CHANNEL = 1031
GMS_MSG_DO_FACTORY_DEFAULT_RADIO = 1032
GMS_MSG_DO_FACTORY_DEFAULT_SCRAMBLE = 1033
GMS_MSG_DO_FACTORY_DEFAULT_TP = 1034
GMS_MSG_DO_FACTORY_DFAULT_SAT = 1035
GMS_MSG_DO_REMOTE_CONTROL = 1040
GMS_MSG_DO_POWER_SWITCH = 1041
GMS_MSG_DO_TV_RADIO_SWITCH = 1042
GMS_MSG_DO_STB_RESTART = 1043
GMS_MSG_DO_SLEEP_TIMER_SET = 1050
GMS_MSG_DO_PASSWORD_SWITCH_SET = 1051
GMS_MSG_DO_NEW_PASSWORD_SET = 1052
GMS_MSG_DO_SCREEN_LOCK = 1053
GMS_MSG_DO_RS232_DEBUG_ENABLE = 1054
GMS_MSG_DO_FAV_GROUP_RENAME = 1055
GMS_MSG_DO_PASSWORD_CHECK = 1056
GMS_MSG_DO_INPUT_PASSWORD_CANCEL = 1057
GMS_MSG_DO_INPUT_METHOD_DISMISS = 1058
GMS_MSG_DO_INPUT_METHOD_KEY_CODE_SET = 1059
GMS_MSG_DO_SAT_SELECTED_CHANGE = 1060
GMS_MSG_DO_INCOMMING_CALL_NUM_DISPLAY = 1061
GMS_MSG_DO_SMS_NUM_DISPLAY = 1062
GMS_MSG_DO_MAX_VALUE = 1999

# Notify message types (GMS_MSG_NOTIFY_*)
GMS_MSG_NOTIFY_INPUT_PASSWORD_CANCEL = 2000
GMS_MSG_NOTIFY_PLAYING_CHANNEL_CHANGED = 2001
GMS_MSG_NOTIFY_CHANNEL_LIST_CHANGED = 2002
GMS_MSG_NOTIFY_MUTE_STATE_CHANGED = 2003
GMS_MSG_NOTIFY_TV_RADIO_SWITCH = 2004
GMS_MSG_NOTIFY_EVENT_TIMER_CHANGED = 2005
GMS_MSG_NOTIFY_PSW_DIALOG_SHOW = 2006
GMS_MSG_NOTIFY_PSW_DIALOG_DISMISS = 2007
GMS_MSG_NOTIFY_CONTROL_SETTING_CHANGED = 2008
GMS_MSG_NOTIFY_SAT_NO_SELECT_CHANGED = 2009
GMS_MSG_NOTIFY_NEW_RS232_DATA_PRINTED = 2010
GMS_MSG_NOTIFY_INPUT_METHOD_POPUP = 2011
GMS_MSG_NOTIFY_INPUT_METHOD_DISMISS = 2012
GMS_MSG_NOTIFY_FAV_GROUP_NAME_CHANGED = 2013
GMS_MSG_NOTIFY_POWER_SWITCH_CHANGED = 2014
GMS_MSG_NOTIFY_CLIENT_TYPE_BECOME_MASTER = 2015
GMS_MSG_NOTIFY_FACTORY_DEFAULT_ALL = 2016
GMS_MSG_NOTIFY_FACTORY_DEFAULT_CHANNEL = 2017
GMS_MSG_NOTIFY_FACTORY_DEFAULT_RADIO = 2018
GMS_MSG_NOTIFY_SAT_LIST_CHANGED = 2019
GMS_MSG_NOTIFY_NEW_PVR_ADD = 2020
GMS_MSG_NOTIFY_PVR_RENAME = 2021
GMS_MSG_NOTIFY_PVR_DELETE = 2022
GMS_MSG_NOTIFY_USB_DISK_REMOVE = 2023
GMS_MSG_NOTIFY_STB_IP_CHANGED = 2024
GMS_MSG_NOTIFY_SDS_ENABLED = 2025
GMS_MSG_NOTIFY_SDS_DISABLED = 2026
GMS_MSG_NOTIFY_STB_SCREEN_UNLOCKED = 2027
GMS_MSG_NOTIFY_MAX_VALUE = 2999

# Command message types (GMS_MSG_CMD_*)
GMS_MSG_CMD_INIT = 3000
GMS_MSG_CMD_DEINIT = 3001
GMS_MSG_CMD_CACULATE_USER_DATA_LENGTH = 3002
GMS_MSG_CMD_CACULATE_CHANNEL_DATA_LENGHT = 3003
GMS_MSG_CMD_RETURN_PRINT_MEM_ADDR = 3004

# GChat message types
GMS_MSG_GCHAT_REQUEST_ROOM_INFO = 100
GMS_MSG_GCHAT_REQUEST_NEW_MSG = 101
GMS_MSG_GCHAT_REQUEST_BLACK_LIST = 102
GMS_MSG_GCHAT_REQUEST_SETTINGS = 103
GMS_MSG_GCHAT_REQUEST_PROGRAM_INFO = 104
GMS_MSG_GCHAT_REQUEST_USERNAME = 105
GMS_MSG_GCHAT_REQUEST_MAX = 300
GMS_MSG_GCHAT_DO_START = 1100
GMS_MSG_GCHAT_DO_EXIT = 1101
GMS_MSG_GCHAT_DO_SEND_MSG = 1102
GMS_MSG_GCHAT_DO_BLOCK_UNBLOCK_USER = 1103
GMS_MSG_GCHAT_DO_CHANGE_SETTING = 1104
GMS_MSG_GCHAT_DO_USER_RENAME = 1105
GMS_MSG_GCHAT_DO_MAX = 1300
GMS_MSG_GCHAT_NOTIFY_LOGOUT = 2100
GMS_MSG_GCHAT_NOTIFY_ROOM_INFO_CHANGED = 2101
GMS_MSG_GCHAT_NOTIFY_NEW_MSG = 2102
GMS_MSG_GCHAT_NOTIFY_USER_NAME_CHANGED = 2103
GMS_MSG_GCHAT_NOTIFY_UI_SETTING_CHANGED = 2104
GMS_MSG_GCHAT_NOTIFY_MAX = 2300

# Spectrum message types
GMS_MSG_SPE_REQUEST_SPECTRUM_INFO = 301
GMS_MSG_SPE_REQUEST_SPECTRUM_SETTING = 302
GMS_MSG_SPE_REQUEST_MAX = 400
GMS_MSG_SPE_DO_SET_SPAN_AND_CENT_FRE = 1301
GMS_MSG_SPE_DO_SET_STATE_VH = 1302
GMS_MSG_SPE_DO_SET_STATE_22K = 1303
GMS_MSG_SPE_DO_SET_STATE_DISEQC = 1304
GMS_MSG_SPE_DO_SET_REF = 1305
GMS_MSG_SPE_DO_MAX = 1400

# Response codes (GMS_RESPONSE_*)
GMS_RESPONSE_NO_ERROR = 0
GMS_RESPONSE_FAIL = 1
GMS_RESPONSE_FORMAT_ERROR = 2
GMS_RESPONSE_NO_ENOUGH_MEMORY = 3
GMS_RESPONSE_POINTER_INVALID = 4
GMS_RESPONSE_TIMEOUT = 5
GMS_RESPONSE_BEYOND_SUPPORT_CLIENT_NUM = 6
GMS_RESPONSE_CREATE_MESSAGE_FAILED = 7
GMS_RESPONSE_CREATE_TASK_FAILED = 8
GMS_RESPONSE_PASSWORD_ERROR = 9
GMS_RESPONSE_CREATE_DATA_FILE_FAILED = 10
GMS_RESPONSE_BAD_PARAMETER = 11
GMS_RESPONSE_DEBUG_ERROR = 12
GMS_RESPONSE_NET_ERROR = 13
GMS_RESPONSE_COMPRESS_FAILED = 14
GMS_RESPONSE_EDIT_EVENT_TIMER_REPEAT = 15
GMS_RESPONSE_CHANNEL_RECORDED = 16
GMS_RESPONSE_STB_IS_MENU_STATE = 17
GMS_RESPONSE_NOT_SUPPORT_USB = 18
GMS_RESPONSE_USB_NOT_CONNECT = 19
GMS_RESPONSE_USB_NOT_READY = 20

# Event max
GMS_MSG_EVENT_MAX = 9999

# GSCMD internal commands
GSCMD_OBTAIN_MESSENGER = 4096
GSCMD_START_SEND_DEBUG_DATA = 4097
GSCMD_RECV_DATA_FINISH = 4098
GSCMD_RECV_DEBUG_DATA_FINISH = 4099
GSCMD_TO_SEND_EMAIL = 4100
GSCMD_SEND_EMAIL_FINISH = 4101
GSCMD_COMPRESS_DEBUG_FILE = 4102
GSCMD_SEND_DATA_TO_ACTIVITY = 4103
GSCMD_UPDATE_CHANNEL_LIST_FAILED = 4104
GSCMD_SEND_EMAIL_EXCEPTION = 4105
GSCMD_NOTIFY_SOCKET_CLOSED = 4112
GSCMD_NOTIFY_BROADCAST_LOGIN_INFO_UPDATED = 4113
GSCMD_PLAY_SAT2IP_CHANNEL_FAILED = 4114
GSCMD_REFRESH_SAT_LIST = 4115
GSCMD_GET_IP_BY_SN = 4116
GSCMD_STB_IN_STANDBY = 4117
GSCMD_NOTIFY_CALL_AND_SMS_REMIND_CHANGED = 4118

# Structure types
STRUCT_CHANNEL_LIST = 0
STRUCT_SLEEP_TIMER = 1
STRUCT_PARENT_CONTROL = 2
STRUCT_SOFTWARE_INFO = 3
STRUCT_EVENT_TIMER = 4
STRUCT_STREAM_DATA_INFO = 5
STRUCT_PROGRAM_EPG = 6
STRUCT_CONFIRM_OK = 7
STRUCT_CHANNEL_PASSWORD = 8
STRUCT_STB_TIME = 9
STRUCT_FAVOR_GROUP = 10
STRUCT_CONTROL_SETTING = 11
STRUCT_CHANNEL_TYPE = 12
STRUCT_CURRENT_SORT_TYPE = 13
STRUCT_STB_INFO = 14
STRUCT_ONLY_ONE_DATA = 15
STRUCT_SAT2IP_RETURN = 16
STRUCT_ASK_STB_SETTING_WHEN_LOGIN = 17
STRUCT_SAT_LIST = 18
STRUCT_TP_LIST = 19
STRUCT_PVR_LIST = 20
STRUCT_GCHAT_START = 21
STRUCT_GCHAT_ROOM_INFO = 22
STRUCT_GCHAT_NEW_MSG = 23
STRUCT_GCHAT_BLACK_LIST = 24
STRUCT_GCHAT_SETTING = 25
STRUCT_GCHAT_PROGRAM_INFO = 26
STRUCT_GCHAT_USER_NAME = 27
STRUCT_SPECTRUM_INFO = 28
STRUCT_SPECTRUM_SETTING = 29

# Channel list types
CHANNEL_LIST_TYPE_ALL = 0
CHANNEL_LIST_TYPE_FTA = 1
CHANNEL_LIST_TYPE_SCRAMBLE = 2
CHANNEL_LIST_TYPE_HD = 3
CHANNEL_LIST_TYPE_TV = 0
CHANNEL_LIST_TYPE_RADIO = 1

# Favor list types
FAVOR_LIST_TYPE_NEWS = 4
FAVOR_LIST_TYPE_MOVIES = 5
FAVOR_LIST_TYPE_MUSIC = 6
FAVOR_LIST_TYPE_SPPORTS = 7
FAVOR_LIST_TYPE_EDUCATION = 8
FAVOR_LIST_TYPE_WEATHER = 9
FAVOR_LIST_TYPE_CHILDREN = 10
FAVOR_LIST_TYPE_CULTURE = 11

# EPG timer types
EPG_TIMER_TYPE_NO_TIEMR = 0
EPG_TIMER_TYPE_VIEW_TIEMR = 1
EPG_TIMER_TYPE_RECORD_TIEMR = 2

# Timer select
TIMER_SELECT_START_TIME = 0
TIMER_SELECT_STOP_TIME = 1

# IP address types
INTERNAL_IP_ADDRESS = 0
EXTERNAL_IP_ADDRESS = 1

# Channel limits
CHANNEL_MAX_AUDIO_PID = 32
CHANNEL_MAX_SUBTITLE_PID = 10
MAX_CHANNEL_LIST_TYPE = 12
LOGIN_HISTORY_LIST_ITEM_MAX = 10

# File names
SEND_CHANNEL_FILENAME = "Channel_Data.sdx"
SEND_USER_FILENAME = "User_Data.sdx"
SEND_FLASH_FILENAME = "All_Flash_Data.bin"
SEND_RS232_FILENAME = "Rs232_Output.txt"
SEND_STB_SCREENSHOTS_FILENAME = "ScreenShots.bmp"

# Handshake messages
UPNP_HANDSHAKE_MSG_MOBILE = "HANDSHAKE_MOBILE"
UPNP_HANDSHAKE_MSG_MOBILE_LIST = "HANDSHAKE_MOBILE_LIST"
